version: '3.8'

services:
  web:
    build: ./recettes
    # command: gunicorn elisasrecipe.wsgi --bind 0.0.0.0:8000 --reload
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./recettes/:/usr/src/recettes/
    ports:
      - 8000:8000
    env_file:
      - ./recettes/.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  minio:
    image: minio/minio
    hostname: "minio"
    volumes:
      - ./minio:/minio_files
    env_file:
      - ./recettes/.env
    command: 'minio server /minio_files --console-address ":9001"'
    logging:
      driver: none
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  postgres_data: